eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      url: http://localhost:8764
    api-b:
      path: /api-b/**
      url: http://localhost:8765