spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zouchengli/microservice-repository
          search-paths: repo
          default-label: master
          username:
          password:
server:
  port: 8888